#! /bin/sh

sxhkd &
unclutter &
sh ~/.config/scripts/polybar_main.sh &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

bspc rule -a Chromium-browser follow=off desktop='^1'
bspc rule -a Emacs state=tiled desktop='^2'
bspc rule -a TelegramDesktop desktop='^4'
bspc rule -a discord desktop='^5'
